### ISSUE TITLE
please provide a license file

### ISSUE THREAD

**Issue by keszybz** [harryhaaren/openAV-presets#1]
Hi,
we'd like to package openAV-presets for Fedora, to make them more accessible for users, but the lack of explicit licensing prevents that.

Thanks!

**Comment by schnitzeltony** [comment]
A 'bit' delayed but I kindly ask you for the same.

**Comment by harryhaaren** [comment]
Thanks for the ping @schnitzeltony, and sorry I didn't get to this earlier @keszybz!
